#!/bin/sh
# Print the Homebrew formula for a release, from that release's SHA256SUMS.
#
#   packaging/homebrew.sh 0.1.9 dist/SHA256SUMS > Formula/deconflict.rb
#
# The formula installs the prebuilt release archives rather than building from
# source, so a brew install gets the same bytes the checksums already vouch for.
set -eu

version=${1:?usage: homebrew.sh VERSION SHA256SUMS}
sums=${2:?usage: homebrew.sh VERSION SHA256SUMS}
base="https://github.com/cloudcons/deconflict-cli/releases/download/v$version"

sum() {
	s=$(awk -v f="deconflict_${version}_$1.tar.gz" '$2 == f || $2 == "*" f { print $1 }' "$sums")
	[ -n "$s" ] || { echo "homebrew.sh: no checksum for $1 in $sums" >&2; exit 1; }
	echo "$s"
}

block() {
	cat <<RUBY
    on_$1 do
      url "$base/deconflict_${version}_$2.tar.gz"
      sha256 "$(sum "$2")"
    end
RUBY
}

cat <<RUBY
# Generated by packaging/homebrew.sh in cloudcons/deconflict-cli on each
# release. Edits here are overwritten by the next one.
class Deconflict < Formula
  desc "Advisory intention claims and negotiated agreements for coding agents"
  homepage "https://github.com/cloudcons/deconflict-cli"
  version "$version"
  license "Apache-2.0"

  on_macos do
$(block arm darwin_arm64)
$(block intel darwin_amd64)
  end

  on_linux do
$(block arm linux_arm64)
$(block intel linux_amd64)
  end

  def install
    bin.install "deconflict"
  end

  def caveats
    <<~EOS
      Wire deconflict into the coding agents you run with:
        deconflict install --agent all
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/deconflict version")
  end
end
RUBY
